String patientid = "";
String patientname = "";
String district = "";
int red = 0, yellow = 0;
String selected = "";
bool others = false;
String caretaker = "";
String phoneNum = "";
Map<String, String> otherdetails = {};
String answersfor = "";
String selectedLanguage = 'English';
